#ifndef CONFIG_H
#define CONFIG_H

#define PROGRAM_LOAD_ADDRESS 0x200
#define CHIP8_MEMORY_SIZE 4096
#define NUMBER_OF_REGISTERS 16
#define SIZE_OF_STACK 16
#define TOTAL_KEYS 16

#define EMULATOR_WINDOW_TITLE "CHIP8 Emulator"
#define CHIP8_WINDOW_RATIO 1/2;
#define CHIP8_WIDTH 64
#define CHIP8_HEIGHT 32
#define WINDOW_MULTIPLIER 20
#define PIXEL_SIZE 1
#define DEFAULT_SPRITE_HEIGHT 5

#define CLOCK_SPEED 500
#define CLOCK_PERIOD 1000/CLOCK_SPEED
#define EXECS_PER_DT 8

#endif
